### ISSUE TITLE
Click on LixiLotus logo or Home to refresh page (and load Home page)

### ISSUE THREAD

**Issue by nghiacc** [bcProFoundation/lixilotus#539] opened 2023-03-20 04:59 UTC
![Image](https://user-images.githubusercontent.com/19528107/226250694-905a90ec-870c-43d6-aeb5-85d00dae23cd.png)

**Comment by DinhChien2001** [comment] 2023-03-23 06:49
Steps to reproduce issue: 
- Use 2 accounts in 2 different browsers: edge and chrome
- Use one account in 1 browser to create a post
- Refresh/click on home button or switch page back and forth to home button
- Expect: The new post is shown in the post list
- Actual: The new post is not shown
Conclusion: The issue root cause is not that click on home button not fresh the page. The root cause is due to a bug in caching the post list.

Assign to @KenNguyen-dev to fix.

**Closed** 2023-05-09 06:48 UTC
