### ISSUE TITLE
Categories corrections

### ISSUE THREAD

**Issue by nghiacc** [bcProFoundation/lixilotus#762] opened 2023-05-26 12:37 UTC
- "Natural" should be "Nature"
Add more categories:
- "Real Estate"
- "Agriculture"
- "Permaculture"
- "Humanitarian"

**Comment by vince8x** [comment] 2023-05-27 14:15
Merged to master. @Huygon764 please help to check the issue on the dev environment after the issue is deployed.

**Comment by Huygon764** [comment] 2023-05-28 12:51
Tested on dev environment @vince8x

**Closed** 2023-05-31 00:48 UTC
